# SQLite環境用のDocker Compose override設定
# 使用方法: docker compose -f docker-compose.yml -f docker-compose.sqlite.yml --env-file .env.sqlite up

services:
  # バックエンドをSQLite環境用に設定変更
  backend:
    env_file:
      - .env.sqlite
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    depends_on:
      - db-init

  # MySQL関連サービスを無効化
  mysql:
    profiles:
      - disabled

  mysql-init:
    profiles:
      - disabled

  # SQLite初期化サービスを有効化
  db-init:
    profiles: []